<?php
require_once 'PHPUnit/Framework.php';

require_once '/var/www/ormmanager/include/TemplateHandler.php';

/**
 * Test class for TemplateHandler.
 * Generated by PHPUnit on 2012-01-24 at 11:49:38.
 */
class TemplateHandlerTest extends PHPUnit_Framework_TestCase
{

    /**
     * @todo Implement testProcess().
     */
    public function testProcess()
    {
        $tplHandler = new BaseTemplateHandler("../templates/class.tpl");

	    $tplHandler->process();
    }
}
?>
